<a href="https://colab.research.google.com/github/aakashr30/Heart-Disease-Prediction-Using-Decision-Tree-Classifier/blob/main/day_6(10_5_2022)_project_5_decision_tree_Grid_Search_%5BHEART_DISEASE_PREDICTION%5D_Csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as numpy
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/0 (1).MKCE/4.Decision Tree/2 Project/Heart Disease Prediction/Dataset/HeartDisease.csv")

In [ ]:
data

age  gender  chest_pain  rest_bps  cholestrol  fasting_blood_sugar  \
0     63       1           3       145         233                    1   
1     37       1           2       130         250                    0   
2     41       0           1       130         204                    0   
3     56       1           1       120         236                    0   
4     57       0           0       120         354                    0   
..   ...     ...         ...       ...         ...                  ...   
298   57       0           0       140         241                    0   
299   45       1           3       110         264                    0   
300   68       1           0       144         193                    1   
301   57       1           0       130         131                    0   
302   57       0           1       130         236                    0   

     rest_ecg  thalach  exer_angina  old_peak  slope  ca  thalassemia  target  
0           0      150            0       2.3      0   0            1       1  
1           1      187            0       3.5      0   0            2       1  
2           0      172            0       1.4      2   0            2       1  
3           1      178            0       0.8      2   0            2       1  
4           1      163            1       0.6      2   0            2       1  
..        ...      ...          ...       ...    ...  ..          ...     ...  
298         1      123            1       0.2      1   0            3       0  
299         1      132            0       1.2      1   0            3       0  
300         1      141            0       3.4      1   2            3       0  
301         1      115            1       1.2      1   1            3       0  
302         0      174            0       0.0      1   1            2       0  

[303 rows x 14 columns]

In [ ]:
data.columns

Index(['age', 'gender', 'chest_pain', 'rest_bps', 'cholestrol',
       'fasting_blood_sugar', 'rest_ecg', 'thalach', 'exer_angina', 'old_peak',
       'slope', 'ca', 'thalassemia', 'target'],
      dtype='object')

In [ ]:
data['cholestrol'].describe()

count    303.000000
mean     246.264026
std       51.830751
min      126.000000
25%      211.000000
50%      240.000000
75%      274.500000
max      564.000000
Name: cholestrol, dtype: float64

In [ ]:
data.info

<bound method DataFrame.info of      age  gender  chest_pain  rest_bps  cholestrol  fasting_blood_sugar  \
0     63       1           3       145         233                    1   
1     37       1           2       130         250                    0   
2     41       0           1       130         204                    0   
3     56       1           1       120         236                    0   
4     57       0           0       120         354                    0   
..   ...     ...         ...       ...         ...                  ...   
298   57       0           0       140         241                    0   
299   45       1           3       110         264                    0   
300   68       1           0       144         193                    1   
301   57       1           0       130         131                    0   
302   57       0           1       130         236                    0   

     rest_ecg  thalach  exer_angina  old_peak  slope  ca  thalassem

In [ ]:
x = data.drop(['target'],axis=1)
y = data['target']

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=1)

In [ ]:
print(x_test.shape)
print(x_train.shape)
print(y_test.shape)
print(y_train.shape)

(76, 13)
(227, 13)
(76,)
(227,)


In [ ]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()

In [ ]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
pre = model.predict(x_test)

In [ ]:
model.predict_proba(x_test)

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.

In [ ]:
x_test.shape

(76, 13)

In [ ]:
accuracy_score(y_test,pre)

0.7368421052631579

In [ ]:
confusion_matrix(y_test,pre)

array([[27,  8],
       [12, 29]])

In [ ]:
z = classification_report(y_test,pre)
print(z)

              precision    recall  f1-score   support

           0       0.69      0.77      0.73        35
           1       0.78      0.71      0.74        41

    accuracy                           0.74        76
   macro avg       0.74      0.74      0.74        76
weighted avg       0.74      0.74      0.74        76



In [ ]:
# load libraries
from sklearn import decomposition, datasets
from sklearn import tree
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler

In [ ]:
# Load the iris flower data
dataset = datasets.load_iris()

In [ ]:
#X = dataset.data
#y = dataset.target

In [ ]:
#print(X)

In [ ]:
#print(y)

In [ ]:
# Create an scaler object
sc = StandardScaler()

In [ ]:
# Create a pca object
pca = decomposition.PCA()    

In [ ]:
# Create a decisiontree regression object with an L2 penalty
decisiontree = tree.DecisionTreeClassifier()    

In [ ]:
# Create a pipeline of three steps. First, standardize the data.
# Second, tranform the data with PCA.
# Third, train a Decision Tree Classifier on the data.
pipe = Pipeline(steps=[('sc', sc), 
                       ('pca', pca),
                       ('decisiontree', decisiontree)])

In [ ]:
# Create Parameter Space
# Create a list of a sequence of integers from 1 to 30 (the number of features in X + 1)
n_components = list(range(1,X.shape[1]+1,1))    

In [ ]:
# Create lists of parameter for Decision Tree Classifier
criterion = ['gini', 'entropy']
max_depth = [4,6,8,12]

In [ ]:
# Create a dictionary of all the parameter options 
# Note has you can access the parameters of steps of a pipeline by using '__’
parameters = dict(pca__n_components=n_components,
                  decisiontree__criterion=criterion,
                  decisiontree__max_depth=max_depth)

In [ ]:
# Conduct Parameter Optmization With Pipeline
# Create a grid search object
clf = GridSearchCV(pipe, parameters) 

In [ ]:
# Fit the grid search
clf.fit(X, y)   

GridSearchCV(estimator=Pipeline(steps=[('sc', StandardScaler()), ('pca', PCA()),
                                       ('decisiontree',
                                        DecisionTreeClassifier())]),
             param_grid={'decisiontree__criterion': ['gini', 'entropy'],
                         'decisiontree__max_depth': [4, 6, 8, 12],
                         'pca__n_components': [1, 2, 3, 4]})

In [ ]:
# View The Best Parameters
print('Best Criterion:', clf.best_estimator_.get_params()['decisiontree__criterion'])

Best Criterion: gini


In [ ]:
print('Best max_depth:', clf.best_estimator_.get_params()['decisiontree__max_depth'])

Best max_depth: 6


In [ ]:
print('Best Number Of Components:', clf.best_estimator_.get_params()['pca__n_components'])

Best Number Of Components: 4


In [ ]:
print(clf.best_estimator_.get_params()['decisiontree'])    

DecisionTreeClassifier(max_depth=6)


In [ ]:
# Use Cross Validation To Evaluate Model
CV_Result = cross_val_score(clf, X, y, cv=4, n_jobs=-1)

In [ ]:
print(CV_Result)

[0.97368421 0.94736842 0.86486486 0.91891892]


In [ ]:
print(CV_Result)

[0.97368421 0.94736842 0.86486486 0.91891892]


In [ ]:
print(CV_Result.std())  /

0.04036664746855959
